### ISSUE TITLE
Participant does not receive invitation

### ISSUE THREAD

**Issue by jireh-sg-leo** [dolbyio-samples/comms-app-web-waiting-room-pubnub#4]
Hi,

I'm trying to run this demo. But, it seems like after I click 'Invite' in the host interface, nothing happens at the participant end. 

VoxeetSDK.notification.on("invitation", ...

is never triggered.

**Comment by FabienLavocat** [comment]
Thank you for reporting this @jireh-sg-leo there was an issue when generating the access token that was preventing the invitation from being received. Check out the latest version of the code, it works as expected now.
